version: "3.9"
services:
  dev:
    container_name: dev_ts
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8090"
    volumes:
      - ./pixi-skia-app:/app
      # - /app/node_modules
    tty: true
    # command: [ "npm", "run", "dev" ]
